# Generated by Django 4.0.4 on 2024-05-09 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. This value may contain only letters, numbers, dots, and underscores.', regex='^[a-zA-Z0-9._]+$')], verbose_name='Username')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='Email')),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=55, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=55, verbose_name='Last Name')),
            ],
        ),
    ]
