# Generated by Django 4.0.4 on 2024-05-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='experiences.experience', verbose_name='Experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='users.user', verbose_name='User')),
            ],
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user'], name='calendareve_user_id_dd246d_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['experience'], name='calendareve_experie_56d0f0_idx'),
        ),
    ]
