# Generated by Django 4.0.4 on 2024-05-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('Outdoor', 'Outdoor Adventure'), ('Water', 'Water Adventure'), ('Air', 'Air Adventure'), ('Extreme', 'Extreme Adventure')], max_length=100, verbose_name='Category')),
            ],
        ),
    ]
