# Generated by Django 4.0.4 on 2024-05-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('contact_info', models.CharField(max_length=100, verbose_name='Contact Info')),
            ],
        ),
    ]
