# Generated by Django 4.0.4 on 2024-05-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='providers.provider', verbose_name='Provider')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='sports.sport', verbose_name='Sport')),
            ],
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['sport'], name='experiences_sport_i_f1ede2_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['provider'], name='experiences_provide_e9cb8b_idx'),
        ),
    ]
