# Generated by Django 4.0.4 on 2024-04-22 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. This value may contain only letters, numbers, dots, and underscores.', regex='^[a-zA-Z0-9._]+$')]),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='adventures__user_id_6c1da5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['experience'], name='adventures__experie_a5f2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user'], name='adventures__user_id_18ee8d_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['experience'], name='adventures__experie_865c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['sport'], name='adventures__sport_i_7664a8_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['provider'], name='adventures__provide_210be2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='adventures__user_id_fa8955_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['experience'], name='adventures__experie_6ee762_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user'], name='adventures__user_id_10b2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['provider'], name='adventures__provide_a8ae21_idx'),
        ),
    ]
